services:
  httpd-service:
    build: ./httpd
    ports:
      - 8080:80
  app:
    build: ./app
    environment:
      # set HTTPD_HOST variable to the name of the httpd service.
      # This is more flexible then just hardcoding the service name.
      # This is similar to some of the GUI container that connect to a
      # database using a host variable.  
      HTTPD-HOST: 'httpd-service'
    ports:
      - 5000:5000